  fields:
  - name: mode
    type: radio-fieldset
    values:
      clean: Create a clean standalone engine
      deploy: Deploy containers from compose.yml
      swarm-join: Connect to an existing swarm cluster
    default: clean
    showIf:
      deploy:
      - name: repo
        type: string
        caption: Compose Repo
        default: https://github.com/vegasbrianc/docker-compose-demo.git
        required: true
        vtype: url
      - name: role
        type: string
        default: cp
        inputType: hidden
      swarm-join:
      - name: role
        type: list
        caption: Role
        values:
          cp: Manager
          worker: Worker
        default: worker
        required: true
      - name: token
        type: string
        caption: Token
        default: ''
        required: true
      - name: host
        type: string
        caption: Host IP
        default: ''
        required: true
        regex: "^(?=\\d+\\.\\d+\\.\\d+\\.\\d+$)(?:(?:25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9][0-9]|[0-9])\\.?){4}$"
        regexText: Invalid IP address format
      clean:
      - name: portainer
        type: checkbox
        caption: Install <a href='https://portainer.io' target='_blank'>Portainer UI</a> - lightweight container management
        value: false
      - name: role
        type: string
        default: cp
        inputType: hidden
